#!/usr/bin/env bash
# Fix Nginx so it listens on port 80 by recreating the missing sites-enabled symlink

# Recreate the default site symlink
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start nginx
service nginx restart
