#!/bin/bash
# Install Nginx if needed
apt-get update -qq
apt-get install -y nginx

# Ensure default site is enabled 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start Nginx
service nginx restart
