#!/usr/bin/env bash
# Script that installs and configures Nginx to serve a page containing "Holberton School"

# Update and install nginx
apt-get update -y
apt-get install -y nginx

# Configure nginx to serve "Holberton School" at root
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart nginx
sudo systemctl restart nginx
