#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page with the text "Ceci n'est pas une page".

apt-get update -y
apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update Nginx configuration
sed -i '/server_name _;/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-enabled/default

service nginx restart
